[package]
name = "crab-crawl"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
http = "1.1.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
scraper = "0.19.0"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
